### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by kndone** [roboqo/GraphTheory#1]
Hello, 

I'm trying to run the code, but every time I try to compile it I got an error GraphView.swift file, on lines 21 & 52 

`CGContextSetLineJoin(context, kCGLineJoinRound);
        CGContextSetLineCap(context, kCGLineCapRound);`

The error says: "Use of unresolved identifier kCGLineJoinRound"

I'll be really glad whether anybody might help me.

Thanks.

**Comment by roboqo** [comment]
Fixed in 1a94b6da8f130568fa4da514a26345cd20724cf6 commit.
